### ISSUE TITLE
Objects should implement tags

### ISSUE THREAD

**Issue by micahkemp-splunk** [splunk/terraform-provider-splunkconfig#13]
Tags would allow for selective fetching of matching objects.

An example config:

```
apps:
  - name: My External App
    id: my_app
    acl:
      read: [*]
      write: [admin]
    tags:
      - generic_acl
```

could permit fetching of only `generic_acl` tagged objects to be handled differently from others:

```
data "splunkconfig_app_names" "generic_acl_app_names" {
  tags = [acl_generic]
}
```

This would grant flexibility to use a single configuration file to define apps that will be packaged right next to apps that will only be used for ACL purposes.  Additionally this concept could be applied to all object types for similar functionality.
